# --- notes ---

# 1.  chat2go uses curly brackets ({}) to imply placeholders
# 2.  spaces inside curly brackets are "optional spaces"
#     meaning they will only appear if the placeholder won't
#     be empty (see chatFormat for example usage)
# 3.  PlaceholderAPI is mostly supported and uses the default
#     placeholder format using % (e.g. %player_name%)


# --- general settings --- #

general:
  # description: if set to false chatting will be disabled
  chatEnabled: true

  # description: bStats will collect anonymous statistics of this server
  statisticsAllowed: true


# --- chat formatting --- #

chatFormatting:
  # description: enables chat formatting
  enabled: true

  # description: set the format
  # chat2go placeholders:
  # - {prefix}
  # - (suffix}
  # - {username}
  # - (message}
  # PlaceholderAPI is supported
  # JSON elements can be used here
  format: "{prefix }{username}{ suffix}&8 » &f{message}"

  # description: enables colored chatting, in 1.16+ hex colors are supported
  # permission: chat2go.chat.color
  # example: &6 turns golden
  # example (1.16+): <#ff0000> turns red
  # example (1.16+): &#ff0000 turns red
  # example (1.16+): #(ff0000) turns red
  translateChatColors: true


# --- chat filtering --- #

chatFilter:
  # description: enables chat filtering for bad words defined in badwords.yml
  # permission: chat2go.bad_word.ignore
  enabled: true

  # description: if chat filtering is enabled, the message containing a bad word will either be completely blocked or censored
  # possible values: [BLOCK, CENSOR]
  filterMode: BLOCK

  # description: if chat filter is enabled, it will block links and ips
  # permission: chat2go.chat.bypass_ip
  linkBlockEnabled: true


# --- anti spam --- #

antiSpam:
  # description: will try it best to prevent chat spamming
  # permission: chat2go.chat.bypass_anti_spam
  enabled: false

  # description: (anti spam) threshold of caps lock detection
  capsThreshold: 0.5

  # description: (anti spam) threshold of spacing detection
  spaceThreshold: 0.3


# --- slow mode --- #

slowMode:
  # description: chatting will be available with a cooldown
  # permission: chat2go.chat.bypass_slow_mode
  enabled: false

  # description: the cooldown given in seconds
  cooldown: 5


# --- join and leave messages --- #

customJoinMessage:
  # description: enable custom join messages
  enabled: true

  # description: disables the join message
  hidden: false

  # description: custom join message format
  # chat2go placeholders:
  # - {prefix}
  # - (suffix}
  # - {username}
  # PlaceholderAPI is supported
  message: "&7[&a+&7] &7{username}"

customLeaveMessage:
  # description: custom leave message
  enabled: true

  # description: disables the leave message
  hidden: false

  # description: custom leave message format
  # chat2go placeholders:
  # - {prefix}
  # - (suffix}
  # - {username}
  # PlaceholderAPI is supported
  message: "&7[&c-&7] &7{username}"


# --- formatting --- #

formatting:
  # description: msg format
  # chat2go placeholders:
  # - {sender}
  # - (receiver}
  # - {message}
  privateMessage: "&8MSG &7[{sender} -> {receiver}]&8: &f{message}"

  # description: broadcast format
  # chat2go placeholders:
  # - {message}
  broadcast: "&f[&cBroadcast&f] {message}"


# --- json elements --- #

mentions:
  # description: if enabled, staff will get notified when a player sends a bad word
  # permission: chat2go.bad_word.notify
  badWordNotificationEnabled: true

  # description: mention other players using '@username‘ in chat
  # permission: chat2go.chat.mention
  chatMentionsEnabled: false

  # description: will play a sound if you get mentioned
  chatMentionSoundEnabled: false

# --- json elements --- #

jsonElements:
  # description: enables the use of the chat2go json feature
  # warning: it may break other chat plugins
  enabled: false

  # description: you can create your own json elements
  elements:
    user: # if jsonElementsEnabled you could now use {user} instead of {username} in formatting
      text: "{username}"
      hoverText: "Send a private message to {username}"
      suggestCommand: "/msg {username} "


# --- do not touch --- #

# description: config version
version: 4