# --- notes ---

# 1.  chat2go uses curly brackets ({}) to imply placeholders
# 2.  spaces inside curly brackets are "optional spaces"
#     meaning they will only appear if the placeholder won't
#     be empty (see chatFormat for example usage)
# 3.  PlaceholderAPI is mostly supported and uses the default
#     placeholder format using % (e.g. %player_name%)


# --- general ---

# description: if set to false chatting will be disabled
chatEnabled: true

# description: config version - please do not change
version: 3


# --- chat formatting ---

# description: enables chat formatting
chatFormatEnabled: true

# description: set the format
# chat2go placeholders:
# - {prefix}
# - (suffix}
# - {username}
# - (message}
# PlaceholderAPI is supported
chatFormat: "{prefix }{user}{ suffix}&7: &f{message}" # in this example "{user}" is a json element (listed at the bottom
                                                      # of the file) in which "{username}" is referred.

# description: enables colored chatting, in 1.16+ hex colors are supported
# permission: chat2go.chat.color
# example: &6 turns golden
# example (1.16+): <#ff0000> turns red
# example (1.16+): &#ff0000 turns red
# example (1.16+): #(ff0000) turns red
translateChatColorsEnabled: true


# --- chat filtering ---

# description: enables chat filtering for bad words defined in badwords.yml
# permission: chat2go.bad_word.ignore
chatFilterEnabled: true

# description: if chat filtering is enabled, the message containing a bad word will either be completely blocked or censored
# possible values: [BLOCK, CENSOR]
chatFilterMode: BLOCK

# description: if enabled, staff will get notified when a player sends a bad word
# permission: chat2go.bad_word.notify
badWordNotificationEnabled: true

# description: if chat filter is enabled, it will block links and ips
# permission: chat2go.chat.bypass_ip
linkBlockEnabled: true


# --- anti spam ---

# description: will try it best to prevent chat spamming
# permission: chat2go.chat.bypass_anti_spam
antiSpamEnabled: false

# description: (anti spam) threshold of caps lock detection
capsThreshold: 0.5

# description: (anti spam) threshold of spacing detection
spaceThreshold: 0.3


# --- slow mode ---

# description: chatting will be available with a cooldown
# permission: chat2go.chat.bypass_slow_mode
slowModeEnabled: false

# description: the cooldown given in seconds
slowModeSeconds: 5


# --- join and leave messages ---

# description: disables the join message
hideJoinMessage: false

# description: custom join message
customJoinMessageEnabled: true

# description: custom join message format
# chat2go placeholders:
# - {prefix}
# - (suffix}
# - {username}
# PlaceholderAPI is supported
customJoinMessage: "&7[&a+&7] &7{username}"

# description: disables the leave message
hideLeaveMessage: false

# description: custom leave message
customLeaveMessageEnabled: true

# description: custom leave message format
# chat2go placeholders:
# - {prefix}
# - (suffix}
# - {username}
# PlaceholderAPI is supported
customLeaveMessage: "&7[&c-&7] &7{username}"


# --- formatting ---

# description: msg format
# chat2go placeholders:
# - {from}
# - (to}
# - {message}
privateMessageFormat: "&8MSG &7[{from} -> {to}]&8: &f{message}"

# description: broadcast format
# chat2go placeholders:
# - {message}
broadcastFormat: "&f[&cBroadcast&f] {message}"


# --- json elements ---

jsonElements:
  user:
    text: "{username}"
    hover-text: "Send a private message"
    suggest-command: "/msg {username} "