# description: if set to false chatting will be disabled
chatEnabled: true

# description: enables chat formatting
chatFormatEnabled: true

# description: set the format
# placeholder api is supported
chatFormat: "{prefix}{username}{suffix}&7: &f{message}"

# description: adds a space after {prefix} - useful for formatting
prefixTrailingSpaceEnabled: true

# description: adds a space before {suffix} - useful for formatting
suffixLeadingSpaceEnabled: true

# description: enables colored chatting, in 1.16+ hex colors are supported
# permission: chat2go.chat.color
# example: &6 turns golden
# example (1.16+): <#ff0000> turns red
# example (1.16+): &#ff0000 turns red
# example (1.16+): #(ff0000) turns red
translateChatColorsEnabled: true

# description: enables chat filtering for bad words defined in badwords.yml
# permission: chat2go.bad_word.ignore
chatFilterEnabled: true

# description: if chat filtering is enabled, the message containing a bad word will either be completely blocked or censored
# possible values: [BLOCK, CENSOR]
chatFilterMode: BLOCK

# description: if enabled, staff will get notified when a player sends a bad word
# permission: chat2go.bad_word.notify
badWordNotificationEnabled: true

# description: if chat filter is enabled, it will block links and ips
# permission: chat2go.chat.bypass_ip
linkBlockEnabled: true

# description: will try it best to prevent chat spamming
# permission: chat2go.chat.bypass_anti_spam
antiSpamEnabled: false

# description: (anti spam) threshold of caps lock detection
capsThreshold: 0.5

# description: (anti spam) threshold of spacing detection
spaceThreshold: 0.3

# description: chatting will be available with a cooldown
# permission: chat2go.chat.bypass_slow_mode
slowModeEnabled: false

# description: the cooldown given in seconds
slowModeSeconds: 5

# description: disables the join message
hideJoinMessage: false

# description: custom join message
customJoinMessageEnabled: true

# description: custom join message format
# placeholder api is supported
customJoinMessage: "&7[&a+&7] &7{username}"

# description: disables the leave message
hideLeaveMessage: false

# description: custom leave message
customLeaveMessageEnabled: true

# description: custom leave message format
# placeholder api is supported
customLeaveMessage: "&7[&c-&7] &7{username}"

# description: msg format
privateMessageFormat: "&8MSG &7[{from} -> {to}]&8: &f{message}"

# description: broadcast format
broadcastFormat: "&f[&cBroadcast&f] {message}"

# do not touch
version: 2