name: chat2go
version: 0.3.4-PRE
author: rex2go
description: chat2go is an easy to use chat management plugin with 1.16 color support

softdepend:
  - Vault
  - PlaceholderAPI
loadbefore:
  - Vault
  - PlaceholderAPI

main: eu.rex2go.chat2go.Chat2Go
api-version: 1.13

commands:
  msg:
    description: Send a private message
    usage: "§cUsage: /<command> <player> <message>"
    permission: chat2go.command.msg
    aliases:
      - tell
  chat2go:
    usage: "§cUsage: /<command>"
    permission: chat2go.command.chat
    aliases:
      - chat
  reply:
    description: Reply to a private message
    usage: "§cUsage: /<command> <message>"
    permission: chat2go.command.msg
    aliases:
      - r
  clearchat:
    description: Clears the chat
    usage: "§cUsage: /<command>"
    permission: chat2go.command.clear_chat
    aliases:
      - cc
  slowmode:
    description: Toggles chat slow mode
    usage: "§cUsage: /<command> <time>"
    permission: chat2go.command.slow_mode
  broadcast:
    description: Broadcasts a message
    usage: "§cUsage: /<command> <message>"
    permission: chat2go.command.broadcast
    aliases:
      - bcast
  autobroadcast:
    description: Automatic broadcasts
    usage: "§cUsage: /<command> <list|add|remove|reload>"
    permission: chat2go.command.auto_broadcast
    aliases:
      - abcast